version: "3"

networks:
  xs2a-net:

volumes:
  consent-management-data:

services:
  # xs2a standalone starter
  xs2a-standalone-starter:
    image: adorsys/xs2a-standalone-starter
    build:
      context: xs2a-standalone-starter
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx256M"
      - SPRING_PROFILES_ACTIVE=mock-qwac
      - XS2A_CMS_ASPSP_PROFILE_BASEURL=${XS2A_CMS_ASPSP_PROFILE_BASEURL:-http://aspsp-profile:8080/api/v1}
      - XS2A_CMS_CONSENT_SERVICE_BASEURL=${XS2A_CMS_CONSENT_SERVICE_BASEURL:-http://consent-management:8080/api/v1}
    ports:
      - "8080:8080"
    networks:
      - xs2a-net
    depends_on:
      - aspsp-profile
      - consent-management

  # ASPSP-PROFILE
  aspsp-profile:
    image: adorsys/xs2a-aspsp-profile
    build:
      context: aspsp-profile/aspsp-profile-server
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx256M"
      - SPRING_PROFILES_ACTIVE=debug_mode
    ports:
      - "48080:8080"
    networks:
      - xs2a-net

  # CONSENT-MANAGEMENT-SYSTEM
  consent-management:
    image: adorsys/xs2a-consent-management
    build:
      context: consent-management/cms-standalone-service
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx512M"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://consent-management-postgres/consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - XS2A_CMS_ASPSP_PROFILE_BASEURL=${XS2A_CMS_ASPSP_PROFILE_BASEURL:-http://aspsp-profile:8080/api/v1}
      - SERVER_KEY=my_secret_for_cms
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=consent
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://consent-management-postgres/consent?currentSchema=consent
      - SPRING_LIQUIBASE_USER=cms
      - SPRING_LIQUIBASE_PASSWORD=cms
    depends_on:
      - consent-management-postgres

  consent-management-postgres:
    image: centos/postgresql-95-centos7
    volumes:
      - consent-management-data:/var/lib/pgsql/data
      - ./consent-management/cms-db-schema/util/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms
    expose:
      - 5432

  npm-centrally-managed-attachment:
    container_name: npm-centrally-managed-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-centrally-managed-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '8081:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      - xs2a-net
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    ipc: host
    restart: unless-stopped
    networks:
      - xs2a-net
    environment:
      # adjust with your own email below
      - user_email=user@email.com
      - nginxproxymanager=true
    volumes:
      - ./appsec-config:/etc/cp/conf
      - ./appsec-data:/etc/cp/data
      - ./appsec-logs:/var/log/nano_agent
    command: /cp-nano-agent --token <TOKEN>  # replace <TOKEN> with your own token below